### ISSUE TITLE
[QUESTION] is this compatible with Java SE?

### ISSUE THREAD

**Issue by neuronsupport** [tommyettinger/BlazingChain#1]
I was wondering if this library is compatible Java SE. From the source, it looks like it is. Have you tested it? Can I decompress something compressed in GWT in Java SE, and vice versa?

**Comment by tommyettinger** [comment]
It is compatible, yes. I'll add some small tests soon. My only concerns with transmission between GWT and Java SE (or Dalvik/ART on Android) are that I've noticed oddities in how GWT works with ints. Internally, a GWT int is a JS double, and GWT doesn't always ensure the values are within the bounds of `Integer.MIN_VALUE` to `Integer.MAX_VALUE`. GWT's ints may lose precision as doubles do if the value gets too large. I haven't yet tested transmission from GWT to Java SE, and I suspect that if there is any issue, it's most likely to occur when a counter or some other value exceeds `Integer.MAX_VALUE` and overflow is expected but does not occur on GWT, though it would on Java SE. I know I can mitigate this issue if it appears by using longs, which are slower on GWT but are ensured accurate across platforms.

**Comment by tommyettinger** [comment]
There's some sample .jar applications to try in the repo now. One is run with `java -jar Producer.jar input.txt output.txt`, where input.txt is something to compress and output.txt should be where to produce the compressed file. The counterpart to that is run with `java -jar Consumer.jar input.txt output.txt`, where input.txt is already compressed and output.txt is optional (if present, it writes the decompressed contents to that file). I need to get a GWT app up and running to test this, but I've tested GWT with BlazingChain before (only with UTF16 mode, though, which seems to behave much better with my Windows OS when saved to a file). The demo that previously used BlazingChain as a library currently uses a trimmed-down version incorporated into another library, with added (low-quality) encryption as a feature so end users can't read saved data as easily for games. The features should be the same. The demo is here, and though it doesn't use BlazingChain directly, the code should be the same: http://tommyettinger.github.io/SquidLib-Demos/babel/index.html . If you change the text in the left field, it should stay saved in LocalStorage (compressed with LZ-String encoding) if you leave the page and come back. I'm leaving this issue open until I can verify that the data stays the same between GWT and Java SE.

**Comment by tommyettinger** [comment]
OK, I can confirm that transmission works between GWT and Java SE. There's a demo app using GWT here, https://tommyettinger.github.io/BlazingChain/ , and you can paste compressed text using URI encoding into it on the right, then click Decompress to see the original at left. You can also compress it in this way, going from left to right. You can generate compressed files with URI encoding using the Producer jar in the root of this repo with `java -jar Producer.jar PrincessOfMars.txt PrincessOfMarsURI.txt URI`, or using whatever file you want instead of PrincessOfMars.txt . I can't really check how well UTF-16 compression works visually because not many fonts cover as much of UTF-16 as UTF-16 mode uses, so my browser might not copy text correctly (changing characters to '?' or something like that). It will work in LocalStorage, though; the demo currently doesn't compress what it puts there (it would mean compressing one String twice), but it could, and it has in the past.
